Feature/login
shinonome-inc/backend-final-assignment-yasuhiro pull request #3
Opened 2023-01-11 09:35 UTC by Yasushi400

ログイン、ログアウト機能を作成しました。
レビューをお願いします。
<img width="558" alt="image" src="https://user-images.githubusercontent.com/44603676/211770459-175ceb95-7bb2-493c-a27f-1e6489882214.png">

2023-01-11 13:56 UTC, shunsuke44 requested changes
いくつかコメントしたので確認お願いします。

2023-01-11 13:56 UTC, shunsuke44 commented on accounts/forms.py
> +    pass
このクラスは特に使っていないようなので削除お願いします。

2023-01-11 13:56 UTC, shunsuke44 commented on accounts/views.py
> +        return render(request, "accounts/profile.html", context)
`get()`をオーバーライドするのみであれば`DetailView`ではなく`View`の継承で良いでしょう。
`DetailView`を継承する理由は`get_context_data()`などをオーバーライドすることによって、`DetailView`の大枠の処理の一部にカスタムのフックの処理を差し込むためであるので、それを踏まえてどのクラスベースビューを用いるのか選択できるようにしましょう。
ちなみにこの場合だとまさに`DetailView`の`get_context_data()`のオーバーライドによって書くことができます。

2023-01-11 13:56 UTC, shunsuke44 commented on accounts/tests.py
> +        self.assertNotIn(SESSION_KEY, self.client.session)
これ元々ログインできていないと思うのですがどうでしょう？
例えば`test_success_get()`の一番上に`assertNotIn(SESSION_KEY...`を持ってきてもテストが通ると思います。
きちんとテストの役割を果たすために一度テストクライアントをログインさせてからログアウトを行うようにしましょう。

2023-01-11 13:56 UTC, shunsuke44 commented on accounts/tests.py
> +        self.assertNotIn(SESSION_KEY, self.client.session)
あと実際にはPOSTリクエストに対するテストなので、メソッド名も`test_success_post()`にしておくといいと思います。

2023-01-11 13:56 UTC, shunsuke44 commented on templates/tweets/home.html
> +<h3><a type="button" href="{% url 'accounts:logout' %}">ログアウト</a></h3>
これちゃんとログアウトできていますか？

2023-01-11 13:56 UTC, shunsuke44 commented on accounts/views.py
> +        return render(request, "accounts/profile.html", context)
加えて`get_username()`はユーザについてユニークな属性の値を取得する意味合いが強いので、ここでは特に使用する必要はなく、プロフィールに表示するのにふさわしい名前を明確に取得するのがいいと思います。
さらに`username`のみ渡すのではなく、`user`オブジェクト自体を渡してしまってテンプレートで属性にアクセスするようにしてしまってもいいと思います。

2023-01-13 15:48 UTC, Yasushi400 commented
いくつか修正しました。
ご確認お願い致します。
Userproflieはこういう感じで書けば大丈夫ですか。
新しいテスト画面です
<img width="548" alt="image" src="https://user-images.githubusercontent.com/44603676/212360978-4b17317a-de14-4320-9efd-263359875709.png">

2023-01-13 15:48 UTC, Yasushi400 commented
<img width="419" alt="image" src="https://user-images.githubusercontent.com/44603676/212361263-51c4e855-9ebc-4975-9f83-521846f918df.png">

2023-01-15 03:00 UTC, shunsuke44 reviewed
コメントしたので確認お願いします。

2023-01-15 03:00 UTC, shunsuke44 commented on accounts/views.py
> +        return User.objects.get(id=self.request.user.id)
これだと自分のプロフィールしか見ることができないので、要件から考えると不適切です。
URLのusernameを使うようにしてください。

2023-01-15 03:00 UTC, shunsuke44 commented on templates/tweets/home.html
> +<h3><a type="button" href="{% url 'accounts:logout' %}">ログアウト</a></h3>
実際にはDjango4.1ではGETでもログアウトはできるようですが、POSTリクエストでLogoutViewをテストしているので、実際のログアウトもGETではなくPOSTリクエストによって行うべきだと思います。
aタグによって発生するHTTPリクエストのメソッドはGETなので、formを使ってLogoutViewにPOSTリクエストを送れるようにしてみてください。
Chromeの開発者ツールなども利用して確かめてみるといいと思います。

2023-01-15 03:00 UTC, shunsuke44 commented on templates/tweets/home.html
> +<h3><a type="button" href="{% url 'accounts:logout' %}">ログアウト</a></h3>
他のログアウトについても同様にお願いします。

2023-01-15 03:00 UTC, shunsuke44 commented on mysite/urls.py
> +    path("/", include("welcome.urls")),
このスラッシュは必要ですか？

2023-01-15 13:10 UTC, shunsuke44 reviewed
コメントしました。

2023-01-15 13:10 UTC, shunsuke44 commented on templates/accounts/profile.html
> +    <a type="button" href="{% url 'accounts:logout' %}">ログアウト</a>
この書き方だとGETリクエストのままですね

2023-01-15 13:25 UTC, shunsuke44 commented
まずUserProfileViewの要件としてURLのusernameで指定されるユーザのプロフィール（名前）を表示しなければいけないということは分かりますか？
つまり`TemplateView`の`get_context_data()`のオーバーライドで上記のユーザを取得するようにしたいということです。
あとは公式ドキュメントのクラスベースビューのトピックガイドや該当クラスのリファレンスガイドを読んでもらえるとヒントになると思います。
それでも分からなければまた聞いてください。

2023-01-16 01:46 UTC, Yasushi400 commented
ヒントありがとうございます。

logoutのpostリクエストについての質問です。
formにpostと{% csrf_token %}を追加することで、処理がpostリクエストとして認められますか。

2023-01-16 02:24 UTC, shunsuke44 reviewed
修正お願いします。

2023-01-16 02:24 UTC, shunsuke44 commented on accounts/views.py
> +        return context
self.request.POSTで取得できるのはPOSTされたデータだけです。
ちゃんと動作確認はしていますか？

2023-01-16 02:24 UTC, shunsuke44 commented on templates/tweets/home.html
> +</form>
そもそもの話ですが、aタグはリンクを表すものであるのでこの場合は正しくないと思います。
単にログインの時と同じようにすれば大丈夫なはずです。

2023-01-16 02:27 UTC, shunsuke44 commented
> ヒントありがとうございます。
> 
> logoutのpostリクエストについての質問です。 formにpostと{% csrf_token %}を追加することで、処理がpostリクエストとして認められますか。

formをちゃんと機能させるためには基本的には<input type="submit">を使うのが一番いいと思います。

2023-01-17 07:27 UTC, Yasushi400 commented
formタグ内でactionを指定すれば、特定のurlにPOSTリクエストが送れるようになりますか。
サイト上では問題なく、指定したページに飛べます。

2023-01-17 07:31 UTC, Yasushi400 commented
ユーザープロファイルについての問題ですか。
ユーザー名はGETでもPOSTでも、どちらもサイト上で表示できました。
調べたところでGETメソッドとPOSTメソッドは違った物らしくて、しかし、submitで送信する情報はPOSTじゃないですか。どうしてGETでもできますか。
また、ユーザープロファイルについてのヒントをいただけますか。

2023-01-17 11:29 UTC, shunsuke44 commented
> formタグ内でactionを指定すれば、特定のurlにPOSTリクエストが送れるようになりますか。 サイト上では問題なく、指定したページに飛べます。

指定したページには飛べてもリクエストとしてはPOSTではなくGETになってしまうと思います．Chtomeの拡張機能などで確認してみてください．

> ユーザープロファイルについての問題ですか。
> ユーザー名はGETでもPOSTでも、どちらもサイト上で表示できました。
> 調べたところでGETメソッドとPOSTメソッドは違った物らしくて、しかし、submitで送信する情報はPOSTじゃないですか。どうしてGETでもできますか。
`request.POST`はdictのようなデータになっており，`get()`で追加の引数を与えずに取得するとエラーが起こるのではなくデフォルトとして`None`が返されます．
またテンプレート側ではコンテキストの`username`ではなく`user.username`にアクセスしているために，エラーが起きずにログインユーザの名前が表示されているのだと思います．この`user`はデフォルトのコンテキストでログインユーザを表しています．なのでおそらくテンプレート内で`username`に直接アクセスしようとすると`None`になっているはずです．

実装のヒントとしては，チュートリアルを参照してコンテキストがどういうものなのかを再度確認するということと，URL内の情報にアクセスするにはどうしたらいいのかを確認すること，あとは[クラスベースビューのトピックガイド](https://docs.djangoproject.com/ja/4.1/topics/class-based-views/intro/)を一通り読んでどのように使うのかということを確認してみるといいと思います．

2023-01-18 10:18 UTC, Yasushi400 commented
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/44603676/213145714-e2039aff-4589-44e7-a392-3edfeb21fadc.png">
これがPOSTという感じですか

2023-01-18 10:19 UTC, Yasushi400 commented
html上でusernameでも表示できるようになりました。

2023-01-18 11:55 UTC, shunsuke44 reviewed
おそらくコンテキストとテンプレート，クラスビューが理解できていないと思います．
コードの写経はしなくてもいいので，Djangoのチュートリアルと前回張ったページをもう一回一通り読んで流れを覚えることをお勧めします．

2023-01-18 11:55 UTC, shunsuke44 commented on accounts/views.py
> +        return get
画面の要件から考えて，ここはリクエストユーザではなくURLの`username`で指定したユーザのプロフィールが見られなければならないので，`request.user.username`ではなくURLからユーザを取得して，存在すればそのユーザーネームを表示するようにしてください．
あとスーパークラスから取得した`context`に`username`を登録してもそれは全く反映されていないのでどちらにせよおかしいです．

2023-01-18 11:55 UTC, shunsuke44 commented on templates/tweets/home.html
> +    <a type="button" href="{% url 'accounts:user_profile' user.username %}">ユーザープロファイル</a>
コンテキストに`username`というキーでユーザ名がきちんと渡されていることを確かめるためにはここが`user.username`ではなく`username`でなければいけません．
今のViewの実装だとエラーが起きるでしょうが，それはテンプレートがおかしいのではなく，Viewがおかしいためにエラーが起こっています．

2023-01-18 16:14 UTC, Yasushi400 commented on templates/tweets/home.html
> +    <a type="button" href="{% url 'accounts:user_profile' user.username %}">ユーザープロファイル</a>
すみません、viewでもtemplateviewでも試してみました。usernameで表示するが出来なかったです。
viewを使ったユーザープロファイルの書き方を教えてもらえませんか。

2023-01-23 04:04 UTC, Yasushi400 commented
get_objectsのオーバーライトの仕方よくわからないので、slugの指定でいきたいと思います。

2023-01-23 08:06 UTC, shunsuke44 requested changes
やり方が分からないから別の方法を取るというのは，良くない考え方です．
基本的にプログラミングでは同じことを何通りもの方法で実装できますが，それぞれを理解した上でパフォーマンスや細かな挙動，読みやすさを考慮して最適なものを選択できる必要があるので，意識して実践してみてください．

2023-01-23 08:06 UTC, shunsuke44 commented on accounts/views.py
> +        )
`DetailView`の`get_object()`と合わせて2回`username`を重複して取得してしまっています．
どちらか一つを使うようにしてください．
また`slug`と`username`で使える文字種が違うので今回の場合`slug`を使うのは良くないです．

2023-01-24 05:34 UTC, shunsuke44 requested changes
いくつかコメントしたので確認お願いします

2023-01-24 05:34 UTC, shunsuke44 commented on accounts/views.py
> +from mysite.settings import LOGIN_REDIRECT_URL
この設定の参照方法は良くありません．
自分のモジュールの`settings`を直接読み込むのではなく，`django.conf import settings`として，`settings.LOGIN_REDIRECT_URL`として参照するようにしてください．[参考](https://docs.djangoproject.com/ja/4.1/topics/settings/#using-settings-in-python-code)

2023-01-24 05:34 UTC, shunsuke44 commented on accounts/views.py
> +    success_url = reverse_lazy(LOGIN_REDIRECT_URL)
ここも

2023-01-24 05:34 UTC, shunsuke44 commented on accounts/views.py
> +    context_object_name = "profile"
`TemplateView`を使うときには`context_object_name`は必要ないです．

2023-01-24 05:34 UTC, shunsuke44 commented on accounts/views.py
> +        context["username"] = get_object_or_404(
ここで実際に取得しているのは`User`オブジェクトなので`username`としてしまうと少しわかりにくいです．
`profile_user`などとするか，きちんと`username`のみを取得して渡すようにした方がいいと思います．

2023-01-24 05:34 UTC, shunsuke44 commented on templates/accounts/profile.html
> +    <p>{{ username }}さん、こんにちは。</p>
ここで参照されるのは`profile`でターゲットとしているユーザなので，ログイン者とは別の人の名前が入る可能性があります．
そう考えるとUIとしてこの表現はあまり適切ではないと思います．

2023-01-24 05:34 UTC, shunsuke44 commented on accounts/tests.py
> +from mysite.settings import LOGIN_REDIRECT_URL, LOGOUT_REDIRECT_URL
ここも

2023-01-24 15:41 UTC, shunsuke44 reviewed
1点だけ細かなところをコメントしました．
他は大丈夫です．

2023-01-24 15:41 UTC, shunsuke44 commented on templates/accounts/profile.html
> +    <p>{{ profile_user }}のプロフィール</p>
これだと今度は`__str__`の実装に左右されるので，より確実に書くなら`profile_user.username`とした方がいいでしょう．

2023-01-25 11:39 UTC, Akinori13 requested changes
良い感じです！！
SignupViewのテストの確認をお願いします！！[参照](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=942589277&range=2:2)

2023-01-25 12:15 UTC, Yasushi400 commented
テストOKです。
テスト画面になります。
<img width="503" alt="image" src="https://user-images.githubusercontent.com/44603676/214560830-aee6b96e-0599-4395-9fe9-5bec1556506a.png">

2023-01-25 13:11 UTC, Akinori13 commented
LGTM

2023-01-25 13:11 UTC, merged