Feature/tweet
shinonome-inc/backend-final-assignment-yasuhiro pull request #7
Opened 2023-03-02 15:27 UTC by Yasushi400

ツイート機能を実装しました。レビューをお願いいたします。

2023-03-03 07:52 UTC, Snak21-FPB reviewed
全体的にきれいにかけていると思います。コメントをコードのところに5件とここに1件しました。
- accountsのTestUserProfileViewも書いてみてください。

2023-03-03 07:52 UTC, Snak21-FPB commented on templates/accounts/profile.html
> +        [ツイート時間] {{tweet.created_at}}
```suggestion
        [ツイート時間] {{ tweet.created_at }}
```
このように`{{` `}}` や `{%` `%}` の間は1スペース入れた方が、統一感もあって読みやすそうです（Linterが聞かない部分なのですべて手で直す必要があります）。

2023-03-03 07:52 UTC, Snak21-FPB commented on templates/base.html
> +      <div class="menber">
```suggestion
      <div class="member">
```
下のも含めて、英語的にはこうですね

2023-03-03 07:52 UTC, Snak21-FPB commented on templates/tweets/create.html
> +{% block title %}<title>Tweet</title>{% endblock %}
```suggestion
{% block title %} Tweet {% endblock %}
```
title ブロックをオーバーライドしているので、もう一度 <title> を入れなくても大丈夫です（DeleteとDetailも同様）。

2023-03-03 07:52 UTC, Snak21-FPB commented on templates/accounts/profile.html
>      </form>
ログアウトのボタンが2つ表示されるようです（おそらくbase.htmlでつくっているもの）。どちらか1つでもよい気がします。

2023-03-03 07:52 UTC, Snak0201 commented on templates/accounts/profile.html
> +        {% for tweet in tweets %}
ここのツイート表示が、常に今ログインしているユーザーのツイートが表示されるようになっているようです。プロフィールページのTweetsにはそのページで表示しているユーザーのツイートのみを表示させてみてください。

2023-03-04 02:19 UTC, Snak21-FPB reviewed
1点だけコメントしました。

2023-03-04 02:19 UTC, Snak21-FPB commented on templates/accounts/profile.html
> +
ここにも改行の`<br>`が必要です。以下のような表示になってしまっています。
```
a
詳細 b
詳細
```

2023-03-04 09:57 UTC, Snak21-FPB reviewed
LGTM✅
2次レビューに渡します

2023-03-04 15:52 UTC, TAK848 requested changes
<img width="190" alt="Screenshot 2023-03-05 at 0 01 54" src="https://user-images.githubusercontent.com/41906969/222915768-a081d9c7-f3dc-43df-a154-522b26588c78.png">
最後の空行が抜けているファイルが何個かあるので，
https://github.com/shinonome-inc/backend-final-assignment-yasuhiro/pull/7/files
で確認して修正しましょう！（settings.jsonがせっていされてれば勝手に入ります）

2023-03-04 15:52 UTC, TAK848 commented on .vscode/setting.json
> +  }
ファイル名settings.jsonです！

2023-03-04 15:52 UTC, TAK848 commented on accounts/views.py
> +        context["profile_user"] = get_object_or_404(User, username=self.object)
DetailViewが404の処理もやってくれて取得終わってるので，self.objectだけで大丈夫です

というか，context_object_nameにprofile_userとしていしてあげればcontextに勝手に追加されます

2023-03-04 15:52 UTC, TAK848 commented on tweets/views.py
> +    queryset = model.objects.select_related("user").order_by("?")
sortがランダム順になってそうだけど，投稿順にならべなくてOK？

2023-03-04 17:29 UTC, Yasushi400 commented on tweets/views.py
> +    queryset = model.objects.select_related("user").order_by("?")
すみません、ただ面白半分でやってみただけです。直します。

2023-03-04 17:36 UTC, Yasushi400 commented on accounts/views.py
> +        context["profile_user"] = get_object_or_404(User, username=self.object)
ありがとうございます。
context_object_nameをprofile_userとしときます。

2023-03-06 14:20 UTC, TAK848 approved these changes
LGTM

2023-03-06 14:20 UTC, merged