Feature/follow
shinonome-inc/backend-final-assignment-yasuhiro pull request #8
Opened 2023-03-22 03:10 UTC by Yasushi400

## 受講生の確認事項

- [x] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [x] Django Adminに，今まで作成したモデルを全て登録した
- [x] テスト要件のテストを全て実装した
- [x] CI が全て通った

## １次レビュアーの確認事項

- [x] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-03-22 11:32 UTC, Shiota620 commented
初めてのレビュワーとして作業をするため、手探りで作業を行っているのですがmigrateは行っていますか？
python manage.py showmigrationsですべての項目に×がついていること確認していただきたいです。
**注：**これは間違いの指摘ではなく私の方のgithubの動作確認です。

2023-03-22 11:57 UTC, Yasushi400 commented
<img width="595" alt="image" src="https://user-images.githubusercontent.com/44603676/226897893-cbc54d62-d497-4df3-b2bd-08126176365e.png">
こちらマイグレーションの記録になります。途中で何度もデータベースとモデルを作り直しましたので、最初の物とはちょっと違いはありますが、サイト上での動作は問題なく作動しています。

2023-03-22 16:25 UTC, Shiota620 approved these changes

2023-03-22 16:25 UTC, Shiota620 commented on templates/accounts/profile.html
AさんがログインしているとしてBさんをフォローするときはfollowボタン、フォローを解除するときはunfolloeボタンのみを表示し、自分自身のプロフィール画面を表示するときはfollow/unfollowボタンを表示しないようにすればよりきれいになると思います。

2023-03-22 16:25 UTC, Shiota620 commented on accounts/models.py
> +    follower = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
followerにもrelated_nameをつけた方が良いかもしれません。
その場合、related_nameが逆転しないように注意してください。

参考
https://djangobrothers.com/blogs/related_name/

2023-03-22 16:25 UTC, Shiota620 commented on accounts/views.py
> +            if self.request.user.followings.filter(username=self.user.username).exists():
early ruturnというテクニックがあります。
ぜひ調べて活用してみてください。

適切に使用することでif文の2重ネストをなくし、可読性が向上する場合もあります。

2023-03-23 06:35 UTC, Shiota620 approved these changes

2023-03-23 06:35 UTC, Shiota620 commented on accounts/views.py
> +        else:
elseを使わずにここもif文にする方が良いと思います。

2023-03-23 06:35 UTC, Shiota620 commented on accounts/views.py
> +        else:
early ruturnは慣習的に異常系の処理を手前でリターンし、正常系の処理は最後に残るような書き方をするそうです。
今回の場合はおそらくフォローを解除する処理が正常系に部類されると思います。

2023-03-23 06:35 UTC, Shiota620 commented on templates/accounts/profile.html
自分自身のプロフィールを表示したときにfollowボタンが表示されています。

エラーを表示させるためのボタンは必要ないと思うので、自分自身のプロフィールを表示するときはfollowボタンが表示されないようにしてみましょう。

2023-03-23 06:44 UTC, Shiota620 commented on accounts/views.py
> +        else:
今気が付きましたが、おそらく正常系の処理にif文をつける必要はないと思います。

2023-03-23 07:50 UTC, Shiota620 commented on accounts/views.py
>              messages.add_message(self.request, messages.SUCCESS, "フォローを解除しました。")
正常系の処理は最後に書く方が慣習的に分かりやすいとされているので、思い切ってフォローが解除されたメッセージを表示する処理を最後に移動させましょう。

この時、if文をつける必要はないと思います。

2023-03-23 07:52 UTC, Shiota620 approved these changes

2023-03-23 14:58 UTC, Shiota620 reviewed
一次レビューは終了です。お疲れさまでした。

2023-03-23 16:56 UTC, shunsuke44 requested changes
いくつかコメントをしました。確認お願いします。

2023-03-23 16:56 UTC, shunsuke44 commented on accounts/models.py
> +class Meta:
この`Meta`クラスはネストできていないのでユニーク制約が正しく反映されてないと思うのですが、どうでしょう？

2023-03-23 16:56 UTC, shunsuke44 commented on accounts/models.py
> +    following = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="following_users", on_delete=models.CASCADE)
`User`の`followings`の使い方から考えると、中間テーブルの構造としては「`follower`が`following`をフォローする」という方が正しいと思うのですが、どうでしょうか？

2023-03-23 16:56 UTC, shunsuke44 commented on accounts/migrations/0001_initial.py
今回は最終課題で個人での開発ということに加えてデータベースのデータも無いためいいですが、基本的に`migrations`ファイルを再度一から生成するということはしない方がいいので、そこだけ注意をお願いします。

2023-03-23 16:56 UTC, shunsuke44 commented on accounts/models.py
> +    data_created = models.DateTimeField(auto_now_add=True)
`date_created`ではないでしょうか？
あと、`date_created`は確かに`User`モデルの`date_joined`との一貫性はありますが、個人的には`DateTimeField`を使うなら`created_at`の方が時間の一点をよく表していていいような気がします。個人の好みなので気に入らなければ別でも大丈夫です。

2023-03-23 16:56 UTC, shunsuke44 commented on accounts/views.py
> +        context["traget_user"] = self.user
`target_user`のタイポ？

2023-03-23 16:56 UTC, shunsuke44 commented on accounts/views.py
> +        context["traget_user"] = self.user
`target_user`のタイポ？

2023-03-23 16:56 UTC, shunsuke44 commented on accounts/views.py
> +class FollowingListView(LoginRequiredMixin, ListView):
基本的に`ListView`を使うときは`context_object_name`を指定しておくとテンプレート単体で読んだときにも何が渡されているのかがわかりやすいのでいいと思います。

2023-03-23 16:56 UTC, shunsuke44 commented on accounts/views.py
> +        self.user = get_object_or_404(User, username=self.kwargs["username"])
他では使っていないので`self`をつけない方がいいでしょう。

2023-03-23 16:56 UTC, shunsuke44 commented on accounts/views.py
> +        self.user = get_object_or_404(User, username=self.kwargs["username"])
ここも

2023-03-23 16:56 UTC, shunsuke44 commented on accounts/models.py
> +    following = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="following_users", on_delete=models.CASCADE)
追加で`related_name`の命名をするときには、逆方向に参照されたときに分かりやすい名前を付けた方がいいと思います。
今回の場合で言うと、逆方向に参照された時のモデルは`FriendShip`なので、`follower_users`よりも`follower_friendships`の方がわかりやすいのではないでしょうか？

2023-03-24 01:13 UTC, shunsuke44 reviewed
もう一点だけコメントしました。

2023-03-24 01:13 UTC, shunsuke44 commented on accounts/models.py
> +    following = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="following_users", on_delete=models.CASCADE)
ここも`following_friendships`とした方が良さそうです。

2023-03-24 01:32 UTC, shunsuke44 approved these changes

2023-03-24 01:33 UTC, merged