add like function
shinonome-inc/backend-final-assignment-yasuhiro pull request #9
Opened 2023-03-25 05:03 UTC by Yasushi400

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-03-26 14:51 UTC, nishikou-1216 reviewed
1点だけコメントしたので確認をお願いします。

2023-03-26 14:51 UTC, nishikou-1216 commented on tweets/views.py
> +class UnLikeView(LoginRequiredMixin, View):
UnLikeをUnlikeにした方がいいと思います。

2023-03-26 15:21 UTC, nishikou-1216 commented
1次レビューLGTM

2023-03-27 18:06 UTC, masaya09 requested changes

2023-03-27 18:06 UTC, masaya09 commented on static/js/like.js
> +const LikeAction = async (tweet) => {
javascriptの命名はローワーキャメルケースですので、likeActionに変更しましょう

2023-03-27 18:06 UTC, masaya09 commented on tweets/views.py
> +        context["liked_tweet"] = Like.objects.filter(user=self.request.user).values_list("tweet", flat=True)
命名は liked_tweets といったふうに複数形にした方が良さそうです

2023-03-27 18:06 UTC, masaya09 commented on tweets/models.py
> +        return self.likes.count
```suggestion
    @property
    def liked_count(self):
        return self.likes.count()
```
countはメソッドなので、実行してあげないと実数値返してくれないです。

templateで使えるのテンプレートエンジンのおかげなので、propertyとして使うならメソッド実行させる必要があります。こうすれば、JsonResponseのcontextのところできちんとJSON変換できるようになります。

templateでは、count()でなく、countで表示される理由
これは単純で、テンプレート内で関数実行はできないからですね。代わりに、テンプレートではcountとすることで、count()メソッドを実行させるようになってます。試しに、template内で{{ tweet.likes.count() }}としてみてレンダリングしてみてください。TemplateSyntaxErrorが出ると思います

2023-03-27 18:17 UTC, masaya09 commented on tweets/views.py
> +    def get_context_data(self, **kwargs):
DetailViewなのであまり影響ないですけどユーザーをjoinしておくとクエリ数1つ減らせます

2023-03-28 14:08 UTC, Yasushi400 commented on tweets/views.py
> +    def get_context_data(self, **kwargs):
すみません、これをもっと具体的に説明してくれますか。

2023-03-28 14:36 UTC, masaya09 commented on tweets/views.py
> +    def get_context_data(self, **kwargs):
例えば、HomeVIewではツイート表示のところでユーザー名表示してるため、ユーザーをselect_relatedを用いてjoinしてますよね。これによりN+1を回避したのと同様に、ここのTweetDetailViewでも同じこと言えるということです。ただ、HomeViewと異なりDetailViewはツイートデータ1つしか取ってこないのでN+1と言ってもNの数が1つだからあんま影響ないよね、ということです

2023-03-29 09:11 UTC, masaya09 requested changes

2023-03-29 09:11 UTC, masaya09 commented on tweets/views.py
> +            "liked_count": tweet.likes.count(),
せっかくproperty作成したので、ここは作成したpropertyを使ってはどうでしょうか？

2023-03-29 09:11 UTC, masaya09 commented on tweets/views.py
> +            "liked_count": tweet.likes.count(),
ここも

2023-03-29 09:12 UTC, masaya09 commented on tweets/views.py
> +    def get_context_data(self, **kwargs):
こちら理解できましたか？反応もらえると助かります

2023-03-29 16:37 UTC, Yasushi400 commented on tweets/views.py
> +    def get_context_data(self, **kwargs):
DetailViewではN+1問題しないが、はより詳細な条件を絞れば、実行速度が上がることということですか

2023-03-30 05:35 UTC, masaya09 commented on tweets/views.py
> +    def get_context_data(self, **kwargs):
N＋1問題です。だけど、Nの個数が1つだからそこまで影響ないということです。クエリ1つ減るので実行速度は上がります

2023-03-30 05:38 UTC, masaya09 requested changes
N+1が起きてるのは、TweetDetailViewですのでそれ以外を変更する必要はないです。

2023-03-30 05:38 UTC, masaya09 commented on accounts/views.py
> +        )
ここは別にjoinしなくていいです。tweet_idが取ってこれればいいので、むしろuserをjoinするのはパフォーマンス劣化につながります

2023-03-30 05:38 UTC, masaya09 commented on tweets/views.py
> +        )
ここも同様にjoinしなくていいです。

2023-03-30 06:03 UTC, masaya09 approved these changes
LGTM

2023-03-30 06:03 UTC, merged